//
// Created by kkoz34 on 01.06.2021.
//

#ifndef PROJEKT_ASTEROID_GAMESETUP_H
#define PROJEKT_ASTEROID_GAMESETUP_H

#define WIDTH 1500
#define HEIGHT 1000
#define PLAYER_SPEED 5
#define BULLET_SPEED 10
#define ASTEROID_SPEED_MAX 3
#define PLAYER_RADIUS 20.0f
#define PLAYER_X 500
#define PLAYER_Y 400
#define ROTATION_SPEED 3.0f
#define DEG_RAD M_PI/180
#define BULLET_SIZE 3
#define ASTEROIDS_N 5
#define ASTEROID_RADIUS 100
#define ASTEROID_POINTS 100
#define NEW_ASTEROIDS 5
#define TITLE "Asteroids_kkoz3434"


#endif //PROJEKT_ASTEROID_GAMESETUP_H
