//
// Created by kkoz34 on 01.06.2021.
//

#ifndef PROJEKT_ASTEROID_GAMESETUP_H
#define PROJEKT_ASTEROID_GAMESETUP_H

#define WIDTH 800
#define HEIGTH 600
#define BULLET_SPEED 10
#define ASTEROID_SPEED_MAX 20
#define ASTEROID_SPEED_MIN 10
#define PLAYER_RADIUS
#define TITLE "Asteroids_kkoz3434"


#endif //PROJEKT_ASTEROID_GAMESETUP_H
